name: <environment name>
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - pandas
      - numpy
      - scikit-learn
      - joblib
      - azureml-inference-server-http>=0.8.0
      - inference-schema>=1.5.0


